CC=g++
CXX=g++
RANLIB=ranlib

LIBSRC=sockets.cpp container.cpp
LIBOBJ=$(LIBSRC:.cpp=.o)

CFLAGS = -Wall -std=c++11 -g
CXXFLAGS = -Wall -std=c++11 -g

all: sockets container

sockets: sockets.cpp
container: container.cpp
